In [61]:
import pandas as pd
import datetime
import json

In [2]:
blurb = pd.read_csv('blurb_validation_df.csv', index_col='Unnamed: 0')

In [3]:
oi = pd.read_csv('projects_fin.csv', index_col='Unnamed: 0')

In [74]:
projects = pd.merge(blurb, oi, left_on = 'name', right_on = 'name', how='inner')

In [33]:
projects['launched_year'] = projects.apply(lambda x: x['launched'].split(" ")[0].split("-")[0], axis = 1)
projects['launched_month'] = projects.apply(lambda x: x['launched'].split(" ")[0].split("-")[1], axis = 1)
projects['launched_day'] = projects.apply(lambda x: x['launched'].split(" ")[0].split("-")[2], axis = 1)
projects['launched_date'] = projects.apply(lambda x: x['launched'].split(" ")[0].split("-")[1] + x['launched'].split(" ")[0].split("-")[2], axis = 1)

In [34]:
projects['deadline_dt'] = projects.apply(lambda x: datetime.datetime.strptime(x['deadline'], "%Y-%m-%d").date(), axis = 1)
projects['launched_dt'] = projects.apply(lambda x: datetime.datetime.strptime(x['launched'].split(" ")[0], "%Y-%m-%d").date(), axis = 1)

In [35]:
projects['term'] = projects.apply(lambda x: int(str(x['deadline_dt'] - x['launched_dt']).split(" ")[0]), axis = 1)
projects['term_str'] = projects.apply(lambda x: str(x['term']), axis = 1)

In [36]:
# launch 날짜가 1970년으로 되어있는 row는 삭제
projects_new = projects[lambda x: x['term'] < 100]

In [21]:
projects_new = projects_new.reset_index().drop(['index'], axis = 1)

In [22]:
projects_new['term_str'] = projects_new.apply(lambda x: x['term_str'] if len(x['term_str']) != 1
                                             else '0' + x['term_str'], axis = 1)

In [23]:
# binnarize the dependent variable
projects_new['state_bin'] = projects_new['state_new'].apply(lambda x: 0 if x == 'failed' else 1)

In [24]:
# 10만원 이하로 펀딩 받는 경우는 지움
projects_fin = projects_new[projects_new['usd_goal_real'] > 100]

In [58]:
train_data = projects_fin[['category', 'main_category', 'currency', 'country', 'usd_goal_real', 'state_bin', 'launched_year', 'launched_month', 'term']]

In [59]:
train = pd.DataFrame()

In [64]:
# lode vectorizatino labeling
with open('../non_nlp/cat_labels.json') as json_file:
    data = json.load(json_file)

{'3D Printing': 0,
 'Academic': 1,
 'Accessories': 2,
 'Action': 3,
 'Animals': 4,
 'Animation': 5,
 'Anthologies': 6,
 'Apparel': 7,
 'Apps': 8,
 'Architecture': 9,
 'Art': 10,
 'Art Books': 11,
 'Audio': 12,
 'Bacon': 13,
 'Blues': 14,
 'Calendars': 15,
 'Camera Equipment': 16,
 'Candles': 17,
 'Ceramics': 18,
 "Children's Books": 19,
 'Childrenswear': 20,
 'Chiptune': 21,
 'Civic Design': 22,
 'Classical Music': 23,
 'Comedy': 24,
 'Comic Books': 25,
 'Comics': 26,
 'Community Gardens': 27,
 'Conceptual Art': 28,
 'Cookbooks': 29,
 'Country & Folk': 30,
 'Couture': 31,
 'Crafts': 32,
 'Crochet': 33,
 'DIY': 34,
 'DIY Electronics': 35,
 'Dance': 36,
 'Design': 37,
 'Digital Art': 38,
 'Documentary': 39,
 'Drama': 40,
 'Drinks': 41,
 'Electronic Music': 42,
 'Embroidery': 43,
 'Events': 44,
 'Experimental': 45,
 'Fabrication Tools': 46,
 'Faith': 47,
 'Family': 48,
 'Fantasy': 49,
 "Farmer's Markets": 50,
 'Farms': 51,
 'Fashion': 52,
 'Festivals': 53,
 'Fiction': 54,
 'Film & Video': 55,
 'Fine Art': 56,
 'Flight': 57,
 'Food': 58,
 'Food Trucks': 59,
 'Footwear': 60,
 'Gadgets': 61,
 'Games': 62,
 'Gaming Hardware': 63,
 'Glass': 64,
 'Graphic Design': 65,
 'Graphic Novels': 66,
 'Hardware': 67,
 'Hip-Hop': 68,
 'Horror': 69,
 'Illustration': 70,
 'Immersive': 71,
 'Indie Rock': 72,
 'Installations': 73,
 'Interactive Design': 74,
 'Jazz': 75,
 'Jewelry': 76,
 'Journalism': 77,
 'Kids': 78,
 'Knitting': 79,
 'Latin': 80,
 'Letterpress': 81,
 'Literary Journals': 82,
 'Literary Spaces': 83,
 'Live Games': 84,
 'Makerspaces': 85,
 'Metal': 86,
 'Mixed Media': 87,
 'Mobile Games': 88,
 'Movie Theaters': 89,
 'Music': 90,
 'Music Videos': 91,
 'Musical': 92,
 'Narrative Film': 93,
 'Nature': 94,
 'Nonfiction': 95,
 'Painting': 96,
 'People': 97,
 'Performance Art': 98,
 'Performances': 99,
 'Periodicals': 100,
 'Pet Fashion': 101,
 'Photo': 102,
 'Photobooks': 103,
 'Photography': 104,
 'Places': 105,
 'Playing Cards': 106,
 'Plays': 107,
 'Poetry': 108,
 'Pop': 109,
 'Pottery': 110,
 'Print': 111,
 'Printing': 112,
 'Product Design': 113,
 'Public Art': 114,
 'Publishing': 115,
 'Punk': 116,
 'Puzzles': 117,
 'Quilts': 118,
 'R&B': 119,
 'Radio & Podcasts': 120,
 'Ready-to-wear': 121,
 'Residencies': 122,
 'Restaurants': 123,
 'Robots': 124,
 'Rock': 125,
 'Romance': 126,
 'Science Fiction': 127,
 'Sculpture': 128,
 'Shorts': 129,
 'Small Batch': 130,
 'Software': 131,
 'Sound': 132,
 'Space Exploration': 133,
 'Spaces': 134,
 'Stationery': 135,
 'Tabletop Games': 136,
 'Taxidermy': 137,
 'Technology': 138,
 'Television': 139,
 'Textiles': 140,
 'Theater': 141,
 'Thrillers': 142,
 'Translations': 143,
 'Typography': 144,
 'Vegan': 145,
 'Video': 146,
 'Video Art': 147,
 'Video Games': 148,
 'Wearables': 149,
 'Weaving': 150,
 'Web': 151,
 'Webcomics': 152,
 'Webseries': 153,
 'Woodworking': 154,
 'Workshops': 155,
 'World Music': 156,
 'Young Adult': 157,
 'Zines': 158}

In [67]:
# Assigning a categorical type to categorical varibles and vectorizing the categories for simplification

train['category'] = train_data['category'].map(data['category'])
train['main_category'] = train_data['main_category'].map(data['main_category'])
train['currency'] = train_data['currency'].map(data['currency'])
train['country'] = train_data['country'].map(data['country'])

In [69]:
train[['usd_goal_real', 'launched_year', 'launched_month', 'term', 'state']] = train_data[['usd_goal_real', 'launched_year', 'launched_month', 'term', 'state_bin']]

In [70]:
train['launched_year'] = (train['launched_year']).astype('int')
train['launched_month'] = (train['launched_month']).astype('int')

,category,main_category,currency,country,usd_goal_real,launched_year,launched_month,term,state
0,108,12,3.0,7.0,1533.95,2015,8,59,0
1,93,6,4.0,13.0,30000.00,2017,9,60,0
2,93,6,4.0,13.0,45000.00,2013,1,45,0
3,90,10,4.0,13.0,5000.00,2012,3,30,0
4,55,6,4.0,13.0,19500.00,2015,7,56,0
5,123,7,4.0,13.0,50000.00,2016,2,35,1
6,58,7,4.0,13.0,1000.00,2014,12,20,1
7,41,7,4.0,13.0,25000.00,2016,2,45,0
8,113,4,4.0,13.0,125000.00,2014,4,35,0
9,72,10,4.0,13.0,12500.00,2013,3,30,1
10,62,8,4.0,13.0,200000.00,2016,2,45,0
11,136,8,3.0,7.0,6469.73,2017,4,28,1
12,11,12,4.0,13.0,3000.00,2015,4,30,0
13,52,5,4.0,13.0,20000.00,2013,11,35,1
14,20,5,0.0,1.0,2026.10,2017,8,30,0
15,141,14,4.0,13.0,3500.00,2014,5,30,0
16,90,10,4.0,13.0,10000.00,2010,12,30,1
17,26,1,3.0,7.0,142.91,2015,12,30,1
18,59,7,3.0,7.0,5181.12,2015,3,30,0
19,113,4,4.0,13.0,1000.00,2016,9,31,1
20,113,4,0.0,1.0,1427.35,2015,7,30,1
21,114,0,4.0,13.0,25000.00,2013,2,40,0
22,90,10,4.0,13.0,12000.00,2014,7,30,1
23,153,6,4.0,13.0,10000.00,2013,7,30,0
24,72,10,4.0,13.0,4000.00,2012,4,30,1
25,39,6,4.0,13.0,10000.00,2013,9,30,1
26,70,0,4.0,13.0,3000.00,2015,12,35,0
27,72,10,4.0,13.0,15000.00,2012,8,30,1
28,95,12,1.0,3.0,2396.36,2017,11,60,0
29,90,10,4.0,13.0,2100.00,2016,12,11,1
...,...,...,...,...,...,...,...,...,...
1318,52,5,3.0,7.0,6194.64,2015,5,30,0
1319,55,6,3.0,7.0,9703.24,2013,9,40,0
1320,39,6,4.0,13.0,4000.00,2015,5,45,0
1321,42,10,2.0,4.0,3277.96,2017,8,45,0
1322,26,1,4.0,13.0,3800.00,2013,3,40,1
1323,104,11,4.0,13.0,2000.00,2009,12,83,0
1324,54,12,4.0,13.0,4000.00,2012,5,31,1
1325,113,4,4.0,13.0,10000.00,2011,12,31,0
1326,154,2,4.0,13.0,1000.00,2015,7,30,0
1327,19,12,4.0,13.0,8000.00,2014,3,43,0
1328,2,5,4.0,13.0,6000.00,2017,3,30,0
1329,76,5,0.0,1.0,5737.23,2016,11,30,0
1330,156,10,4.0,13.0,4300.00,2010,8,45,1
1331,37,4,4.0,13.0,45000.00,2014,6,22,1
1332,95,12,4.0,13.0,30000.00,2016,3,45,1
1333,39,6,4.0,13.0,16000.00,2011,9,40,1
1334,2,5,4.0,13.0,20000.00,2015,9,30,0
1335,141,14,4.0,13.0,1000.00,2012,1,30,0
1336,41,7,4.0,13.0,25000.00,2015,12,30,1
1337,76,5,4.0,13.0,1500.00,2015,5,30,0
1338,90,10,4.0,13.0,2800.00,2016,11,37,1
1339,19,12,4.0,13.0,500.00,2015,4,30,1
1340,142,6,4.0,13.0,3000.00,2015,4,30,0
1341,30,10,4.0,13.0,2000.00,2012,12,30,1
1342,72,10,4.0,13.0,1500.00,2012,1,30,1
1343,141,14,3.0,7.0,41828.40,2014,3,10,0
1344,131,13,4.0,13.0,50000.00,2016,9,30,0
1345,26,1,4.0,13.0,8000.00,2012,2,60,1
1346,148,8,4.0,13.0,70000.00,2015,8,30,0
1347,58,7,NaN,NaN,25661.39,2016,4,22,1